import type { Impact, Violation } from '../checks/types.js';
import type { ReportData, IssueGroup, PageGroup } from './views.js';

const IMPACT_LABEL: Record<Impact, string> = {
  critical: 'Critical',
  serious: 'Serious',
  moderate: 'Moderate',
  minor: 'Minor',
};

export function renderReport(data: ReportData): string {
  const generated = escapeHtml(new Date(data.generatedAt).toLocaleString());
  const t = data.totals;
  const total = t.violationNodes;
  return `<!doctype html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8" />
<title>auto-a11y report — ${generated}</title>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<style>${STYLES}</style>
</head>
<body>
<header class="topbar">
  <div class="wrap topbar-inner">
    <div class="brand-group">
      ${LOGO_SVG}
      <div class="brand-text">
        <h1 class="brand">auto-a11y</h1>
        <p class="tagline">Accessibility audit report</p>
      </div>
    </div>
    <div class="topbar-meta">
      <p class="meta">${generated} · ${t.pages} page${t.pages === 1 ? '' : 's'} · ${total} failing instance${total === 1 ? '' : 's'}</p>
      <button type="button" class="theme-toggle" id="themeToggle">Switch to light theme</button>
    </div>
  </div>
</header>

<section class="overview wrap" aria-label="Summary">
  <div class="score-card">
    <div class="donut" style="background:${donutGradient(t.impacts, total)}">
      <div class="donut-center">
        <span class="donut-num">${total}</span>
        <span class="donut-cap">issue${total === 1 ? '' : 's'}</span>
      </div>
    </div>
    <div class="score-meta">
      <p class="score-title">${total === 0 ? 'No violations found' : 'Failing instances'}</p>
      <p class="score-sub">Across ${t.pages} page${t.pages === 1 ? '' : 's'} · ${t.findings} check run${t.findings === 1 ? '' : 's'}</p>
    </div>
  </div>
  ${renderStatCard('critical', t.impacts.critical)}
  ${renderStatCard('serious', t.impacts.serious)}
  ${renderStatCard('moderate', t.impacts.moderate)}
  ${renderStatCard('minor', t.impacts.minor)}
</section>

<div class="toolbar">
  <div class="wrap toolbar-inner">
    <div class="tabs" role="tablist" aria-label="Report views">
      <button type="button" class="tab active" role="tab" id="tab-by-page" aria-selected="true" aria-controls="by-page" data-view="by-page">By page</button>
      <button type="button" class="tab" role="tab" id="tab-by-issue" aria-selected="false" aria-controls="by-issue" data-view="by-issue" tabindex="-1">By issue type</button>
    </div>
    <section class="filters" aria-label="Filters">
      <label class="field"><span>Impact</span>
        <select id="impactFilter">
          <option value="">All</option>
          <option value="critical">Critical</option>
          <option value="serious">Serious</option>
          <option value="moderate">Moderate</option>
          <option value="minor">Minor</option>
        </select>
      </label>
      <label class="toggle"><input type="checkbox" id="hideClean"> <span>Hide clean pages</span></label>
      <label class="toggle"><input type="checkbox" id="expandAll" checked> <span>Expand all</span></label>
    </section>
  </div>
</div>

<main class="wrap">
  <section id="by-page" class="view active" role="tabpanel" aria-labelledby="tab-by-page" tabindex="0">
    ${data.byPage.map(renderPage).join('\n')}
  </section>
  <section id="by-issue" class="view" role="tabpanel" aria-labelledby="tab-by-issue" tabindex="0">
    ${data.byIssue.map(renderIssue).join('\n')}
  </section>
</main>

<footer class="site-footer">
  <div class="wrap">
    Generated by <strong>auto-a11y</strong> · powered by axe-core &amp; Playwright. Automated testing catches a subset of accessibility issues — manual review with assistive technology remains essential.
  </div>
</footer>

<script>${SCRIPT}</script>
</body>
</html>`;
}

function renderStatCard(impact: Impact, n: number): string {
  return `<div class="stat-card impact-${impact}">
    <span class="stat-dot" aria-hidden="true"></span>
    <span class="stat-count">${n}</span>
    <span class="stat-label">${IMPACT_LABEL[impact]}</span>
  </div>`;
}

function renderPage(group: PageGroup): string {
  const hasFindings = group.totalNodes > 0;
  const id = `page-${hash(group.url)}`;
  const sev = hasFindings ? worstImpact(group.impacts) : 'clean';
  const summary = hasFindings
    ? `${group.totalNodes} failing instance${group.totalNodes === 1 ? '' : 's'} across ${group.findings.length} check run${group.findings.length === 1 ? '' : 's'}`
    : 'No violations';
  // Default: open pages that have findings.
  const openAttr = hasFindings ? ' open' : '';
  return `<details class="page-group sev-${sev}${hasFindings ? '' : ' clean'}" data-impacts="${impactsAttr(group.impacts)}" data-clean="${hasFindings ? 'false' : 'true'}"${openAttr}>
  <summary>
    <h2 class="page-title">${escapeHtml(group.pageTitle || group.url)}</h2>
    <div class="page-meta"><code>${escapeHtml(group.url)}</code></div>
    <div class="page-summary">${summary}</div>
  </summary>
  <div class="page-body" id="${id}">
    <p class="page-link"><a href="${escapeHtml(group.url)}" target="_blank" rel="noopener">Open page in new tab ↗</a></p>
    ${group.findings.map(renderFindingBlock).join('\n')}
  </div>
</details>`;
}

function renderFindingBlock(f: { command: string; violations: Violation[]; validations?: { nodes: { target: string; html: string; screenshotPath?: string }[]; description: string }[] }): string {
  const blocks: string[] = [];
  for (const v of f.violations) {
    blocks.push(renderViolation(v, f.command));
  }
  if (f.validations && f.validations.length > 0) {
    for (const val of f.validations) {
      blocks.push(`<div class="validation">
        <div class="validation-head"><span class="ok-badge">PASS</span> ${escapeHtml(val.description)} <span class="count">${val.nodes.length} node(s)</span></div>
        <ul class="nodes-flat">
          ${val.nodes.map((n) => `<li><code>${escapeHtml(n.target)}</code></li>`).join('')}
        </ul>
      </div>`);
    }
  }
  return blocks.join('\n');
}

function renderViolation(v: Violation, source: string): string {
  return `<div class="violation impact-${v.impact}" data-impact="${v.impact}" data-wcag="${v.wcag?.join(',') ?? ''}">
  <header class="violation-head">
    <span class="impact-badge impact-${v.impact}">${IMPACT_LABEL[v.impact]}</span>
    <span class="rule-id">${escapeHtml(v.id)}</span>
    <span class="source-badge">${escapeHtml(source)}</span>
    <span class="count">${v.nodes.length} failing instance${v.nodes.length === 1 ? '' : 's'}</span>
    ${v.wcag?.map((w) => `<span class="wcag-tag">WCAG ${escapeHtml(w)}</span>`).join('') ?? ''}
  </header>
  <p class="violation-help">${escapeHtml(v.help)}${v.helpUrl ? ` <a href="${escapeHtml(v.helpUrl)}" target="_blank" rel="noopener">learn more →</a>` : ''}</p>
  ${v.criteria && v.criteria.length > 0 ? `<ul class="criteria">${v.criteria.map((c) => `<li><a href="${escapeHtml(c.url)}" target="_blank" rel="noopener">${escapeHtml(c.id)} ${escapeHtml(c.title)} (${c.level})</a></li>`).join('')}</ul>` : ''}
  <ol class="nodes">
    ${v.nodes.map((n, i) => renderNode(n, i + 1)).join('\n')}
  </ol>
</div>`;
}

function renderNode(n: { target: string; html: string; failureSummary?: string; screenshotPath?: string }, idx: number): string {
  return `<li class="node">
  <div class="node-head">
    <span class="node-index">#${idx}</span>
    <code class="selector">${escapeHtml(n.target)}</code>
  </div>
  ${n.failureSummary ? `<p class="failure">${escapeHtml(n.failureSummary)}</p>` : ''}
  <pre class="snippet"><code>${escapeHtml(n.html.slice(0, 1500))}${n.html.length > 1500 ? '…' : ''}</code></pre>
  ${n.screenshotPath ? `<a href="${escapeHtml(n.screenshotPath)}" target="_blank" rel="noopener"><img class="shot" src="${escapeHtml(n.screenshotPath)}" alt="Screenshot of the failing element ${escapeHtml(n.target)}" loading="lazy" /></a>` : ''}
</li>`;
}

function renderIssue(issue: IssueGroup): string {
  return `<details class="issue-group sev-${issue.impact}" data-impact="${issue.impact}" data-wcag="${issue.wcag.join(',')}" open>
  <summary>
    <span class="impact-badge impact-${issue.impact}">${IMPACT_LABEL[issue.impact]}</span>
    <h2>${escapeHtml(issue.ruleId)}</h2>
    <span class="count">${issue.totalNodes} failing instance${issue.totalNodes === 1 ? '' : 's'} on ${issue.occurrences.length} page${issue.occurrences.length === 1 ? '' : 's'}</span>
    ${issue.wcag.map((w) => `<span class="wcag-tag">WCAG ${escapeHtml(w)}</span>`).join('')}
  </summary>
  <p class="issue-help">${escapeHtml(issue.help)}${issue.helpUrl ? ` <a href="${escapeHtml(issue.helpUrl)}" target="_blank" rel="noopener">learn more →</a>` : ''}</p>
  ${issue.occurrences.map((occ) => `<div class="occurrence">
    <h3><a href="${escapeHtml(occ.url)}" target="_blank" rel="noopener">${escapeHtml(occ.pageTitle || occ.url)}</a> <span class="count">${occ.nodes.length} instance${occ.nodes.length === 1 ? '' : 's'}</span></h3>
    <ol class="nodes">${occ.nodes.map((n, i) => renderNode(n, i + 1)).join('')}</ol>
  </div>`).join('')}
</details>`;
}

/** Conic-gradient string for the summary donut, segmented by impact share. */
function donutGradient(impacts: Record<Impact, number>, total: number): string {
  if (total <= 0) return 'var(--ok)';
  const order: Array<[Impact, string]> = [
    ['critical', 'var(--sev-critical)'],
    ['serious', 'var(--sev-serious)'],
    ['moderate', 'var(--sev-moderate)'],
    ['minor', 'var(--sev-minor)'],
  ];
  const stops: string[] = [];
  let acc = 0;
  for (const [k, color] of order) {
    const n = impacts[k];
    if (n <= 0) continue;
    const start = (acc / total) * 360;
    acc += n;
    const end = (acc / total) * 360;
    stops.push(`${color} ${start.toFixed(2)}deg ${end.toFixed(2)}deg`);
  }
  return `conic-gradient(${stops.join(', ')})`;
}

/** Highest-severity impact present, for the card accent stripe. */
function worstImpact(impacts: Record<Impact, number>): Impact {
  if (impacts.critical > 0) return 'critical';
  if (impacts.serious > 0) return 'serious';
  if (impacts.moderate > 0) return 'moderate';
  return 'minor';
}

function impactsAttr(impacts: Record<Impact, number>): string {
  return Object.entries(impacts)
    .filter(([, n]) => n > 0)
    .map(([k]) => k)
    .join(',');
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function hash(s: string): string {
  let h = 0;
  for (let i = 0; i < s.length; i++) {
    h = (h * 31 + s.charCodeAt(i)) | 0;
  }
  return Math.abs(h).toString(36);
}

const LOGO_SVG = `<svg class="logo" width="30" height="30" viewBox="0 0 30 30" aria-hidden="true" focusable="false">
  <rect width="30" height="30" rx="8.5" fill="url(#a11y-logo)" />
  <path d="M9 15.4l3.8 3.8L21 11" fill="none" stroke="#fff" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round" />
  <defs><linearGradient id="a11y-logo" x1="0" y1="0" x2="30" y2="30" gradientUnits="userSpaceOnUse">
    <stop stop-color="#7c8cff" /><stop offset="1" stop-color="#a855f7" />
  </linearGradient></defs>
</svg>`;

const STYLES = `
:root { color-scheme: dark light; }
html[data-theme="dark"] {
  --bg: #0a0c10;
  --band: #0e1117;
  --surface: #11151c;
  --surface-2: #171c26;
  --fg: #e7ecf3;
  --fg-strong: #f6f8fc;
  --muted: #98a2b3;
  --border: #222a36;
  --border-strong: #2d3744;
  --primary: #7c8cff;
  --primary-strong: #9aa6ff;
  --ok: #34d399;
  --sev-critical: #ff5d5d;
  --sev-serious: #ffa23e;
  --sev-moderate: #ffd24a;
  --sev-minor: #9aa4b2;
  --code-bg: #05070b;
  --code-fg: #cdd6e4;
  --shadow: 0 1px 2px rgba(0,0,0,0.35), 0 1px 1px rgba(0,0,0,0.2);
  --shadow-lg: 0 10px 30px -12px rgba(0,0,0,0.7);
  --knob: #f6f8fc;
}
html[data-theme="light"] {
  --bg: #f4f6f9;
  --band: #ffffff;
  --surface: #ffffff;
  --surface-2: #f3f5f9;
  --fg: #1c2331;
  --fg-strong: #0c1119;
  --muted: #5b6675;
  --border: #e4e8ef;
  --border-strong: #d2d8e2;
  --primary: #4f46e5;
  --primary-strong: #4338ca;
  --ok: #15803d;
  --sev-critical: #e5484d;
  --sev-serious: #dd7411;
  --sev-moderate: #b9810b;
  --sev-minor: #64748b;
  --code-bg: #0d1320;
  --code-fg: #dde5f0;
  --shadow: 0 1px 2px rgba(15,23,42,0.06), 0 1px 3px rgba(15,23,42,0.08);
  --shadow-lg: 0 14px 32px -14px rgba(15,23,42,0.22);
  --knob: #ffffff;
}
* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--fg);
  font: 14px/1.55 "Inter", -apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", Roboto, sans-serif;
  -webkit-font-smoothing: antialiased; text-rendering: optimizeLegibility; }
a { color: var(--primary); }
a:hover { color: var(--primary-strong); }
:focus-visible { outline: 2px solid var(--primary); outline-offset: 2px; border-radius: 3px; }
summary:focus-visible, .tab:focus-visible { outline: 2px solid var(--primary); outline-offset: -2px; }
@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after { transition: none !important; scroll-behavior: auto !important; }
}
.wrap { width: 100%; max-width: 1180px; margin: 0 auto; padding: 0 28px; }

/* Header */
.topbar { background: var(--band); border-bottom: 1px solid var(--border); }
.topbar-inner { display: flex; align-items: center; justify-content: space-between; gap: 18px; padding: 16px 28px; flex-wrap: wrap; }
.brand-group { display: flex; align-items: center; gap: 12px; }
.logo { display: block; border-radius: 8.5px; box-shadow: 0 2px 8px -2px rgba(124,140,255,0.5); }
.brand-text { display: flex; flex-direction: column; }
.brand { margin: 0; font-size: 16px; font-weight: 700; letter-spacing: -0.2px; color: var(--fg-strong); }
.tagline { margin: 0; font-size: 12px; color: var(--muted); }
.topbar-meta { display: flex; align-items: center; gap: 16px; flex-wrap: wrap; }
.meta { margin: 0; color: var(--muted); font-size: 12.5px; }
.theme-toggle { background: var(--surface-2); color: var(--fg); border: 1px solid var(--border); border-radius: 8px; padding: 7px 13px; cursor: pointer; font: inherit; font-size: 12px; font-weight: 500; transition: border-color 0.15s, background 0.15s; }
.theme-toggle:hover { border-color: var(--border-strong); background: var(--surface); }

/* Overview */
.overview { display: flex; gap: 14px; flex-wrap: wrap; align-items: stretch; padding-top: 24px; padding-bottom: 4px; }
.score-card { flex: 2 1 300px; display: flex; align-items: center; gap: 20px; background: var(--surface); border: 1px solid var(--border); border-radius: 16px; padding: 20px 22px; box-shadow: var(--shadow); }
.donut { width: 88px; height: 88px; border-radius: 50%; position: relative; flex: none; }
.donut-center { position: absolute; inset: 11px; border-radius: 50%; background: var(--surface); display: flex; flex-direction: column; align-items: center; justify-content: center; }
.donut-num { font-size: 24px; font-weight: 750; color: var(--fg-strong); font-variant-numeric: tabular-nums; line-height: 1; }
.donut-cap { font-size: 10.5px; color: var(--muted); text-transform: uppercase; letter-spacing: 0.6px; margin-top: 2px; }
.score-meta { display: flex; flex-direction: column; gap: 3px; }
.score-title { margin: 0; font-size: 16px; font-weight: 650; color: var(--fg-strong); letter-spacing: -0.2px; }
.score-sub { margin: 0; font-size: 12.5px; color: var(--muted); }
.stat-card { flex: 1 1 124px; display: flex; flex-direction: column; gap: 6px; background: var(--surface); border: 1px solid var(--border); border-radius: 16px; padding: 16px 18px; box-shadow: var(--shadow); transition: border-color 0.15s, transform 0.15s; }
.stat-card:hover { border-color: var(--border-strong); transform: translateY(-1px); }
.stat-dot { width: 9px; height: 9px; border-radius: 50%; }
.stat-card.impact-critical .stat-dot { background: var(--sev-critical); }
.stat-card.impact-serious .stat-dot { background: var(--sev-serious); }
.stat-card.impact-moderate .stat-dot { background: var(--sev-moderate); }
.stat-card.impact-minor .stat-dot { background: var(--sev-minor); }
.stat-count { font-size: 27px; font-weight: 750; color: var(--fg-strong); font-variant-numeric: tabular-nums; line-height: 1.05; letter-spacing: -0.5px; }
.stat-label { font-size: 11px; color: var(--muted); text-transform: uppercase; letter-spacing: 0.7px; font-weight: 600; }

/* Sticky toolbar */
.toolbar { position: sticky; top: 0; z-index: 30; background: var(--band); border-top: 1px solid var(--border); border-bottom: 1px solid var(--border); margin-top: 22px; }
.toolbar-inner { display: flex; align-items: center; justify-content: space-between; gap: 16px; padding: 12px 28px; flex-wrap: wrap; }
.tabs { display: inline-flex; gap: 4px; background: var(--surface-2); border: 1px solid var(--border); border-radius: 11px; padding: 4px; }
.tab { background: transparent; border: 0; padding: 7px 15px; font: inherit; font-size: 13px; font-weight: 600; color: var(--muted); cursor: pointer; border-radius: 8px; transition: color 0.15s, background 0.15s, box-shadow 0.15s; }
.tab:hover { color: var(--fg); }
.tab.active { color: var(--fg-strong); background: var(--surface); box-shadow: var(--shadow); }
.filters { display: flex; gap: 16px; align-items: center; flex-wrap: wrap; }
.filters .field { display: flex; align-items: center; gap: 8px; color: var(--muted); font-size: 12.5px; font-weight: 500; }
.filters select { appearance: none; -webkit-appearance: none; padding: 7px 30px 7px 12px; border-radius: 9px; border: 1px solid var(--border); background-color: var(--surface-2); color: var(--fg); font: inherit; font-size: 13px; cursor: pointer; transition: border-color 0.15s;
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12'%3E%3Cpath d='M2.5 4.5l3.5 3.5 3.5-3.5' fill='none' stroke='%238b95a7' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E");
  background-repeat: no-repeat; background-position: right 11px center; }
.filters select:hover { border-color: var(--border-strong); }
.toggle { display: inline-flex; align-items: center; gap: 9px; color: var(--muted); font-size: 12.5px; font-weight: 500; cursor: pointer; }
.toggle input { appearance: none; -webkit-appearance: none; position: relative; width: 36px; height: 20px; border-radius: 999px; background: var(--border-strong); cursor: pointer; flex: none; transition: background 0.15s; margin: 0; }
.toggle input::after { content: ""; position: absolute; top: 2px; left: 2px; width: 16px; height: 16px; border-radius: 50%; background: var(--knob); box-shadow: 0 1px 2px rgba(0,0,0,0.35); transition: transform 0.15s; }
.toggle input:checked { background: var(--primary); }
.toggle input:checked::after { transform: translateX(16px); }

/* Main + cards */
main { padding-top: 24px; padding-bottom: 56px; }
.view { display: none; }
.view.active { display: block; }
.page-group, .issue-group { position: relative; background: var(--surface); border: 1px solid var(--border); border-radius: 14px; margin-bottom: 14px; overflow: hidden; box-shadow: var(--shadow); transition: border-color 0.15s, box-shadow 0.15s; }
.page-group:hover, .issue-group:hover { border-color: var(--border-strong); box-shadow: var(--shadow-lg); }
.page-group::after, .issue-group::after { content: ""; position: absolute; left: 0; top: 0; bottom: 0; width: 3px; background: var(--accent-stripe, var(--border-strong)); }
.sev-critical { --accent-stripe: var(--sev-critical); }
.sev-serious { --accent-stripe: var(--sev-serious); }
.sev-moderate { --accent-stripe: var(--sev-moderate); }
.sev-minor { --accent-stripe: var(--sev-minor); }
.sev-clean, .page-group.clean { --accent-stripe: var(--ok); }
.page-group summary, .issue-group summary { padding: 16px 20px; cursor: pointer; list-style: none; display: flex; flex-wrap: wrap; align-items: center; gap: 12px; user-select: none; }
.page-group summary::marker, .issue-group summary::marker { display: none; }
.page-group summary::before, .issue-group summary::before { content: "›"; color: var(--muted); font-size: 18px; line-height: 1; font-weight: 700; transition: transform 0.15s; display: inline-block; width: 12px; }
.page-group[open] summary::before, .issue-group[open] summary::before { transform: rotate(90deg); }
.page-group summary h2, .issue-group summary h2 { font-size: 15.5px; margin: 0; color: var(--fg-strong); font-weight: 650; letter-spacing: -0.2px; }
.page-title { word-break: break-word; }
.page-link { margin: 0 0 14px; }
.page-link a { font-size: 13px; font-weight: 500; text-decoration: none; }
.page-link a:hover { text-decoration: underline; }
.page-group .page-meta { width: 100%; color: var(--muted); font-size: 12px; padding-left: 28px; }
.page-group .page-meta code { background: transparent; padding: 0; font-family: ui-monospace, SFMono-Regular, monospace; word-break: break-all; }
.page-group .page-summary { font-size: 12px; color: var(--muted); margin-left: auto; white-space: nowrap; }
.page-group.clean .page-summary { color: var(--ok); font-weight: 600; }
.page-body { padding: 6px 20px 18px; }

/* Violation cards */
.violation { position: relative; background: var(--surface-2); border: 1px solid var(--border); border-radius: 12px; padding: 16px 18px; margin-top: 12px; }
.violation::before { content: ""; position: absolute; left: 0; top: 12px; bottom: 12px; width: 3px; border-radius: 3px; background: var(--sev, var(--border-strong)); }
.violation.impact-critical { --sev: var(--sev-critical); }
.violation.impact-serious { --sev: var(--sev-serious); }
.violation.impact-moderate { --sev: var(--sev-moderate); }
.violation.impact-minor { --sev: var(--sev-minor); }
.violation-head { display: flex; gap: 10px; align-items: center; flex-wrap: wrap; }
/* Badge backgrounds are fixed (theme-independent) and dark enough for white
   text to clear WCAG 1.4.3 AA (>=4.5:1) in both themes. */
.impact-badge { padding: 3px 10px; border-radius: 5px; font-size: 10.5px; font-weight: 700; color: #fff; text-transform: uppercase; letter-spacing: 0.5px; }
.impact-badge.impact-critical { background: #b3261d; }
.impact-badge.impact-serious { background: #b2540e; }
.impact-badge.impact-moderate { background: #8c5a00; }
.impact-badge.impact-minor { background: #475569; }
.ok-badge { padding: 3px 9px; border-radius: 5px; font-size: 10.5px; font-weight: 700; background: #1a7f37; color: #fff; text-transform: uppercase; letter-spacing: 0.5px; }
.rule-id { font-family: ui-monospace, SFMono-Regular, monospace; font-size: 13px; font-weight: 600; color: var(--fg-strong); }
.source-badge { font-size: 10.5px; padding: 3px 8px; background: var(--surface); border: 1px solid var(--border); border-radius: 5px; color: var(--muted); font-weight: 500; }
.count { font-size: 12px; color: var(--muted); font-weight: 500; margin-left: auto; white-space: nowrap; }
.wcag-tag { font-size: 10.5px; padding: 3px 8px; background: var(--surface); color: var(--muted); border: 1px solid var(--border); border-radius: 5px; font-weight: 500; }
.violation-help { color: var(--fg); margin: 12px 0 0; font-size: 13px; }
.violation-help a, .issue-help a { font-weight: 500; }
.criteria { font-size: 12px; color: var(--muted); padding-left: 18px; margin: 8px 0 0; }
.criteria li { margin: 2px 0; }
.criteria a { text-decoration: none; }
.criteria a:hover { text-decoration: underline; }
.nodes { padding-left: 0; list-style: none; margin: 14px 0 0; }
.nodes-flat { padding-left: 18px; color: var(--muted); font-size: 12px; margin: 8px 0 0; }
.node { background: var(--surface); border: 1px solid var(--border); border-radius: 10px; padding: 12px 14px; margin-bottom: 10px; }
.node:last-child { margin-bottom: 0; }
.node-head { display: flex; align-items: center; gap: 10px; margin-bottom: 8px; }
.node-index { font-family: ui-monospace, SFMono-Regular, monospace; font-size: 11px; color: var(--muted); background: var(--surface-2); padding: 2px 8px; border-radius: 999px; border: 1px solid var(--border); }
.selector { display: inline-block; font-family: ui-monospace, SFMono-Regular, monospace; padding: 3px 8px; background: var(--surface-2); border: 1px solid var(--border); border-radius: 6px; font-size: 12px; color: var(--fg); word-break: break-all; }
.failure { color: var(--fg); font-size: 12.5px; margin: 8px 0; padding: 9px 12px; background: var(--surface-2); border-left: 3px solid var(--sev-serious); border-radius: 0 6px 6px 0; }
.snippet { background: var(--code-bg); color: var(--code-fg); padding: 11px 13px; border-radius: 8px; overflow: auto; font-size: 12px; max-height: 230px; line-height: 1.5; margin: 8px 0 0; }
.snippet code { font-family: ui-monospace, SFMono-Regular, monospace; }
.shot { display: block; max-width: 360px; margin-top: 10px; border: 1px solid var(--border); border-radius: 8px; }
.validation { padding: 14px 16px; margin-top: 12px; background: var(--surface-2); border: 1px solid var(--border); border-radius: 12px; }
.validation-head { font-size: 13px; color: var(--fg); display: flex; align-items: center; gap: 9px; flex-wrap: wrap; }
.issue-group summary h2 { font-family: ui-monospace, SFMono-Regular, monospace; font-size: 14px; color: var(--fg-strong); }
.issue-help { padding: 0 20px 14px; color: var(--fg); font-size: 13px; }
.occurrence { padding: 14px 20px; border-top: 1px solid var(--border); }
.occurrence h3 { font-size: 13.5px; margin: 0 0 10px; display: flex; align-items: center; gap: 10px; flex-wrap: wrap; font-weight: 600; }
.occurrence h3 a { text-decoration: none; }
.occurrence h3 a:hover { text-decoration: underline; }

/* Footer */
.site-footer { border-top: 1px solid var(--border); background: var(--band); }
.site-footer .wrap { padding-top: 22px; padding-bottom: 22px; color: var(--muted); font-size: 12.5px; }
.site-footer strong { color: var(--fg); font-weight: 650; }

.hidden { display: none !important; }
@media (max-width: 760px) {
  .wrap { padding: 0 16px; }
  .topbar-inner, .toolbar-inner { padding: 12px 16px; }
  .topbar-meta { width: 100%; justify-content: space-between; }
  .overview { padding-top: 18px; }
  .score-card { flex-basis: 100%; }
  .stat-card { flex-basis: calc(50% - 7px); }
  .toolbar-inner { gap: 12px; }
  .filters { gap: 12px; }
  .page-group .page-summary { margin-left: 0; width: 100%; padding-left: 28px; }
}
`;

const SCRIPT = `
(function() {
  // localStorage access throws on opaque/sandboxed origins (and some file://
  // setups); guard it so theme persistence never breaks the rest of the script.
  const safeGet = (k) => { try { return localStorage.getItem(k); } catch (e) { return null; } };
  const safeSet = (k, v) => { try { localStorage.setItem(k, v); } catch (e) {} };

  const html = document.documentElement;
  const stored = safeGet('a11yTheme');
  if (stored) html.setAttribute('data-theme', stored);
  const themeBtn = document.getElementById('themeToggle');
  const syncBtn = () => themeBtn.textContent = html.getAttribute('data-theme') === 'dark' ? 'Switch to light theme' : 'Switch to dark theme';
  syncBtn();
  themeBtn.addEventListener('click', () => {
    const next = html.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
    html.setAttribute('data-theme', next);
    safeSet('a11yTheme', next);
    syncBtn();
  });

  const tabs = Array.from(document.querySelectorAll('.tab'));
  const views = document.querySelectorAll('.view');
  function activateTab(tab, setFocus) {
    tabs.forEach((t) => {
      const selected = t === tab;
      t.classList.toggle('active', selected);
      t.setAttribute('aria-selected', selected ? 'true' : 'false');
      t.tabIndex = selected ? 0 : -1;
    });
    const target = tab.getAttribute('data-view');
    views.forEach((v) => v.classList.toggle('active', v.id === target));
    if (setFocus) tab.focus();
  }
  tabs.forEach((tab, i) => {
    tab.addEventListener('click', () => activateTab(tab, false));
    tab.addEventListener('keydown', (e) => {
      let next = null;
      if (e.key === 'ArrowRight' || e.key === 'ArrowDown') next = tabs[(i + 1) % tabs.length];
      else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') next = tabs[(i - 1 + tabs.length) % tabs.length];
      else if (e.key === 'Home') next = tabs[0];
      else if (e.key === 'End') next = tabs[tabs.length - 1];
      if (next) { e.preventDefault(); activateTab(next, true); }
    });
  });

  const impactFilter = document.getElementById('impactFilter');
  const hideClean = document.getElementById('hideClean');
  const expandAll = document.getElementById('expandAll');

  function applyFilters() {
    const impact = impactFilter.value;
    document.querySelectorAll('.violation').forEach((node) => {
      const ni = node.getAttribute('data-impact') || '';
      node.classList.toggle('hidden', impact && ni !== impact);
    });
    document.querySelectorAll('.issue-group').forEach((node) => {
      const ni = node.getAttribute('data-impact') || '';
      node.classList.toggle('hidden', impact && ni !== impact);
    });
    document.querySelectorAll('.page-group').forEach((p) => {
      const isClean = p.getAttribute('data-clean') === 'true';
      let hidden = false;
      if (hideClean.checked && isClean) hidden = true;
      if (impact) {
        const impacts = (p.getAttribute('data-impacts') || '').split(',');
        if (!impacts.includes(impact)) hidden = true;
      }
      p.classList.toggle('hidden', hidden);
    });
  }
  impactFilter.addEventListener('change', applyFilters);
  hideClean.addEventListener('change', applyFilters);

  expandAll.addEventListener('change', () => {
    const on = expandAll.checked;
    document.querySelectorAll('.page-group, .issue-group').forEach((d) => {
      d.open = on;
    });
  });
})();
`;
